### ISSUE TITLE
If the Title attribute is empty (in WordPress admin) it should be empty in navigation

### ISSUE THREAD

**Issue by simonwimell** [puikinsh/Sparkling#102]
The inc/navwalker.php is adding a title attribute to the nav links, even if none is provided in the menu editor. It should be empty instead of duplicating the navigation label.

**Comment by lutrov** [comment]
I've looked into this and in `inc/navwalker.php`, line 79:

Instead of:

`$atts['title']  = (empty( $item->attr_title ) || ( (strpos($item->attr_title, 'fa-') !== false) || (strpos($item->attr_title, 'glyphicon-') !== false) ) ) ? $item->title : $item->attr_title;`

Should be:

`$atts['title']  = (empty( $item->attr_title ) || ( (strpos($item->attr_title, 'fa-') !== false) || (strpos($item->attr_title, 'glyphicon-') !== false) ) ) ? '' : $item->attr_title;`
