### ISSUE TITLE
Feature Request - Popular Posts Widget should also display posts which have higher visites

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#104]
The Sparkling Popular Posts Widget consider the post popular when it has more number of comments. In short it works on number of comments posted and not on post views but it would be helpful if it considers post views or provide users to choose any of these options.

Related Topic :

https://colorlib.com/wp/forums/topic/sparkling-popular-posts-widget-doesnt-work/

**Comment by cristianraiber** [comment]
This could never be implemented as a stand-alone feature, as it wouldn't be approved on w.org. It would have to depend on a 3rd party plugin. Since there doesn't seem to be much request for this, I think it would be better closed. 

If I'm wrong about this, and there's actually a lot of request for such a feature, we could look into integrating with a plugin that counts unique posts views.

cc @puikinsh @vinoddalvi

**Comment by cristianraiber** [comment]
I agree @vinoddalvi .
