### ISSUE TITLE
Check for "Recomended" typo

### ISSUE THREAD

**Issue by giucu91** [puikinsh/Sparkling#195]

**Comment by cristianraiber** [comment]
@giucu91 - there was only one (visible) typo re. this. There are multiple variables / function names that have this typo that I don't believe should be changed due to backwards compatible. 

🕊 All front-facing typos have been fixed in: https://github.com/puikinsh/Sparkling/pull/194/commits/8cf315d4b4281fbfd59365929731646b47a7e397
