### ISSUE TITLE
Make the top level menu item clickable and link to access its content

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#38]
Provided the solution in the following reply

https://colorlib.com/wp/forums/topic/correct-menu-structure/#post-25916

**Comment by BurlesonBrad** [comment]
@FreeWPTP open that link again and you'll see my reply over there as well.  Surely if a person chooses a page as their top level navigation item the (#) should be disabled and the actual page be the link, unfortunately that's not the case

page1>page1A
            page2B
            page3C
page2>page2A
            page2B
            page2C
page3>page3A
            page3B
            page4C
all those being normal pages
Unfortunately, even when the top level is set to a good old normal page, the top level menu items still yield nothing but a (#) link (instead of linking to the actual page).

**Comment by FreeWPTP** [comment]
@BurlesonBrad  IT's working fine using the solution posted in this reply https://colorlib.com/wp/forums/topic/correct-menu-structure/page/2/#post-29846

**Comment by puikinsh** [comment]
Fixed on #68
