### ISSUE TITLE
Feature Request - Add support for WP-PageNavi and style it

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#59]
The following popular WP-PageNavi plugin provides easy way to display posts pagination and many themes supports it so i think we should also support it.

https://wordpress.org/plugins/wp-pagenavi/

**Comment by puikinsh** [comment]
Good idea! 

Here is some related information where I already explained how to implement WP-PageNavi: https://colorlib.com/wp/forums/topic/how-to-add-numeric-pagination/

Of course it would be a better to support it by default. 

Since Sparkling theme is based on Bootstrap this or similar solution might come in handy to use Bootstrap built in pagination with WP-Pagenavi: http://calebserna.com/bootstrap-wordpress-pagination-wp-pagenavi/

**Comment by puikinsh** [comment]
Added on https://github.com/puikinsh/Sparkling/pull/67
