### ISSUE TITLE
Sparkling Social Widget not working

### ISSUE THREAD

**Issue by alexandrevicenzi** [puikinsh/Sparkling#91]
After an update Sparkling Social Widget stop working.

I can't find where I can configure this widget anymore. Or it simple doesn't work.

Any help?

**Comment by infario** [comment]
the Social icons are added as menu now. You can use use custom menu widget  with the social icon menu

**Comment by FreeWPTP** [comment]
In the latest version of theme we have changed the social icons functionality to enhance it.

Now you can create social icons as described below.

1. Create a menu like any other menu in the admin area of your site under Appearance -> Menus .
2. Use the correct urls in the menu items, so for twitter it must be twitter.com for facebook it must be facebook.com. Otherwise URLs won't get recognized and you will get squares without icons. 
3. Set theme location for this menu as "Social Links"
4. Use Sparkling Social Widget in the Sidebar

**Comment by alexandrevicenzi** [comment]
Thanks @FreeWPTP, I'll take a look. :+1:
