### ISSUE TITLE
Menu title is glyphicon

### ISSUE THREAD

**Issue by alexandrevicenzi** [puikinsh/Sparkling#93]
Hi,

I was wondering why menu titles are `attr_title`. I thought this was to show an icon before menu name. In my case, if i put mouse over menu, it show `fa fa-line-chart` and not the title.

[Here](https://github.com/puikinsh/Sparkling/blob/58501be3ca15d185860cca4d1ea604e96a09aa32/inc/navwalker.php#L79) is the code that do this.

If you take a look [here](https://github.com/puikinsh/Sparkling/blob/58501be3ca15d185860cca4d1ea604e96a09aa32/inc/navwalker.php#L112), the same attribute is used to add a class to menu span.

**Comment by FreeWPTP** [comment]
The menu titles are the text added in menu option "Title Attribute" in the admin area and if it's not present then it displays "Navigation Label" as menu title.

Now we have added the functionality in the theme that if any text having fa- is added in "Title Attribute"  menu option then it should display text from "Navigation Label" so that the text `fa fa-line-chart` will not be displayed as menu title.
